// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqtndsrcpjfbtvlqjmze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxdG5kc3JjcGpmYnR2bHFqbXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODIyNTksImV4cCI6MjA3MDE1ODI1OX0.804CJqGIp6b4M3zATDEjm8f872cTLEyLztMBhLU4Hxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});